name: Framework

on:
  pull_request:
    branches:
      - main
      - release-2.[6-9]

jobs:
  fw-kind-tests:
    name: KinD
    uses: stolostron/governance-policy-framework/.github/workflows/kind.yml@release-2.6
